### ISSUE TITLE
Premier jet.

### ISSUE THREAD

**Issue by addel** [addel/My-family-organizer#1]
Please les gars laissez moi commit le premier jet, je fait ça ce soir.

**Comment by marcpicaud** [comment]
Pas de soucis :) fyi ya plein de projets cool pour nous aider : 
* https://github.com/bartonhammond/snowflake
* https://github.com/react-community/create-react-native-app
* https://github.com/infinitered/ignite
* https://github.com/futurice/pepperoni-app-kit

**Comment by addel** [comment]
Ok pour moi
