### ISSUE TITLE
Backlog + Release Planning

### ISSUE THREAD

**Issue by marcpicaud** [addel/My-family-organizer#2]
Extrait de l'intra : 

> A partir du brief marketing :
> 
> * Construire un Product backlog priorisé
> * Construire le release planning qui sera appliqué sur la cadence 3 (1 release/semaine)
> 
> **Livrable: Backlog produit, release planning**

**Comment by aurelben** [comment]
mon marco j'ai commencer un backlog sur github project, je te laisse regarder ;)
